<?php

/**
 * Implementation of hook_block_info().
 */
function samplemodule_block_info() {
  $blocks['my-block-id'] = array(
    'info' => t('SAMPLE MODULE BLOCK'),
  );
  return $blocks;
}
 
/**
 * Implementation of hook_block_view().
 */
function samplemodule_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'my-block-id':
      $block['subject'] = t('SAMPLE MODULE BLOCK NAME');
      $block['content'] = samplemodule_contents();
      break;
  }
  return $block;
}
 
/**
 * custom html block
 * @return string
 */
function samplemodule_contents() {
  return '
    </p><div class="body">
      Hello Scale, this is a example custom block!
    </div><p>
  ';
}